try{
    aleee("Ola n√£o deu erro");
}catch(err){
    console.log("Erro: ", err)
}